version: '3'
services:
  web:
    build: .
    ports:
      - '3003:3003'
  db:
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/node-docker

volumes:
  db-data:
